import { Router, urlencoded } from 'express';
import { authRouter } from '../modules/auth/auth.routes';
import { authenticated } from '../modules/auth/auth.middleware';
import { providersRouter } from '../modules/providers/providers.routes';
import { peopleRouter } from '../modules/people/people.routes';
import { eventsRouter } from '../modules/events/events.routes';
import { venuesRouter } from '../modules/venues/venues.routes';
import { checkinRouter } from '../modules/checkin/checkin.routes';
import { adminRouter } from '../modules/crm/admin';
import { ticketingRouter } from '../modules/ticketing/ticketing.routes';
import { communicationsRouter } from '../modules/communications/routes';
import { templatesRouter } from '../modules/communications/templates.routes';
import { segmentsRouter } from '../modules/segments/segments.routes';
import { viewsRouter } from '../modules/views/views.routes';
import { campaignsRouter } from '../modules/campaigns/campaigns.routes';
import { knowledgeRouter } from '../modules/knowledge/routes';
import { aiRouter } from '../modules/ai/routes';
import { dashboardRouter } from '../modules/dashboard/dashboard.routes';
import { searchRouter } from '../modules/search/search.routes';
import { privacyRouter } from '../modules/privacy/privacy.routes';
import { tasksRouter } from '../modules/tasks/tasks.routes';
import { notificationsRouter } from '../modules/notifications/notifications.routes';
import { jobsRouter } from '../modules/jobs/jobs.routes';
import { documentRoutes } from '../modules/documents/documents.routes';
import { documentFileRoutes } from '../modules/documents/document-files.routes';
import { choreographerRoutes } from '../modules/choreographers/choreographers.routes';
import { choreographerAssignmentRoutes } from '../modules/choreographers/finance.routes';
import { automationsRouter } from '../modules/automations/automations.routes';
import { financeRouter, inboundWebhooksRouter } from '../modules/finance/finance.routes';
import { aiPlatformRouter } from '../modules/ai/platform.routes';
import { platformRouter } from '../modules/platform/platform.routes';
import { telegramNotificationsRouter } from '../modules/telegram-notifications/routes';

const router = Router();
router.use('/auth', authRouter);
// Provider callbacks cannot carry a staff session; each handler re-fetches authoritative state.
router.use('/webhooks/inbound', urlencoded({ extended: false, limit: '10kb' }), inboundWebhooksRouter);
router.use(authenticated);
router.use('/dashboard', dashboardRouter);
router.use('/search', searchRouter);
router.use('/privacy', privacyRouter);
router.use('/people', peopleRouter);
router.use('/events', eventsRouter);
router.use('/venues', venuesRouter);
router.use('/check-in', checkinRouter);
router.use('/providers', providersRouter);
router.use('/conversations', communicationsRouter);
router.use('/templates', templatesRouter);
router.use('/segments', segmentsRouter);
router.use('/views', viewsRouter);
router.use('/campaigns', campaignsRouter);
router.use('/knowledge', knowledgeRouter);
router.use('/tasks', tasksRouter);
router.use('/notifications', notificationsRouter);
router.use('/telegram-notifications', telegramNotificationsRouter);
router.use('/jobs', jobsRouter);
router.use('/documents', documentFileRoutes);
router.use('/documents', documentRoutes);
router.use('/choreographers', choreographerRoutes);
router.use('/choreographer-assignments', choreographerAssignmentRoutes);
router.use('/automations', automationsRouter);
router.use(financeRouter);
router.use(aiPlatformRouter);
router.use(platformRouter);
router.use(aiRouter);
router.use(ticketingRouter);
router.use(adminRouter);

export default router;
