import fs from 'fs/promises';
import * as path from 'path';
import { Jimp } from 'jimp';
import { ROOT_DIR } from './paths';

const isDev = process.env.MODE === 'development';
const url = isDev ? 'http://localhost:8080' : process.env.CLIENT_URL;

export const imageUpload = async (file: Express.Multer.File, folderNaam: string) => {

    if (!file) return null;

    // file.filename is generated by multer's storage config (uuid + extension) —
    // never build it from file.originalname, which is attacker-controlled and can
    // contain path traversal sequences.
    const newClientName = file.filename;

    const uploadDir = path.resolve(ROOT_DIR, 'public', 'upload', folderNaam)
    const newPath = path.join(uploadDir, newClientName);

    try {
        await fs.mkdir(uploadDir, { recursive: true });

        await fs.rename(file.path, newPath);

        const img = await Jimp.read(newPath);
        img.resize({ w: 450 });
        // await img.write(newPath as `${string}.${string}`);

        const clientFileURL = `${url}/upload/${folderNaam}/${newClientName}`;
        return clientFileURL;

    } catch (error) {
        console.error('Ошибка при загрузке и обработке изображения:', error);
        await fs.unlink(newPath).catch(() => {});
        throw error;
    }
}
