import { aiConfig, type AiConfig } from '../../config/ai.config';
import {
    emailClassificationSchema,
    type EmailClassification,
    type NormalizedEmailInput,
    type LlmClient,
} from './email-assistant.service';
import { emailDraftSchema, type DraftContext, type DraftLlmClient, type EmailDraft } from './draft.service';
import { buildReplySubject } from '../communication/email/email-smtp.service';
import { DEFAULT_PROMPT_CONTENT, PrismaAiPromptRepository, type AiPromptRepository } from './prompt-library.service';
import { DRAFT_PROVIDERS, type LlmCallMetric } from './draft-provider';
import { buildRagV2Prompt } from './rag-v2/context-builder';

// Below this retrieval score, knowledge is treated as too weak to answer from confidently — see
// KnowledgeRetrievalService's own default (0.35) for the floor below which a chunk isn't
// returned at all; this is a stricter, separate threshold for "confident enough to draft without
// manual review", not for "relevant enough to retrieve".
const CONFIDENT_KNOWLEDGE_SCORE = 0.55;

const ollamaResponseSchema = (value: unknown): string => {
    if (!value || typeof value !== 'object' || typeof (value as { response?: unknown }).response !== 'string') {
        throw new Error('Ollama response did not contain a text response');
    }
    return (value as { response: string }).response;
};

const extractOllamaTokenUsage = (value: unknown): { promptTokens?: number; completionTokens?: number } => {
    if (!value || typeof value !== 'object') return {};
    const body = value as { prompt_eval_count?: unknown; eval_count?: unknown };
    return {
        promptTokens: typeof body.prompt_eval_count === 'number' ? body.prompt_eval_count : undefined,
        completionTokens: typeof body.eval_count === 'number' ? body.eval_count : undefined,
    };
};

// `instructions` is the user-editable part — the active (or overridden) AiPrompt's content,
// resolved by the caller via prompt-library.service.ts. Everything appended after it is the
// per-email data the model must act on, and is never part of the editable prompt: a saved prompt
// can rewrite the model's persona/rules, but can never accidentally omit the actual email.
const buildClassificationPrompt = (instructions: string, input: NormalizedEmailInput, repair?: string) => [
    instructions,
    repair ? `Your previous output was invalid. Repair it and return raw JSON only (no markdown). Invalid output: ${repair.slice(0, 2000)}` : '',
    `FROM: ${input.fromAddress}`,
    `SUBJECT: ${input.subject}`,
    `BODY: ${input.normalizedBody}`,
].filter(Boolean).join('\n');

export interface OllamaLlmClientOptions {
    config?: AiConfig;
    fetchImpl?: typeof fetch;
    promptRepository?: AiPromptRepository;
    // Use a specific saved prompt (active or not) for this client instance instead of the slot's
    // active one — how the "Симуляция письма" panel lets an admin test a candidate prompt without
    // activating it (and therefore without touching real production emails).
    promptOverrides?: { classificationPromptId?: number; draftBodyPromptId?: number };
    onMetric?: (metric: LlmCallMetric) => void;
}

const LANGUAGE_NAMES_RU: Record<EmailClassification['language'], string> = {
    nl: 'нидерландском', en: 'английском', ua: 'украинском', ru: 'русском', unknown: 'том же, что и письмо клиента',
};

// Only the reply BODY is generated by the model. Every other EmailDraft field is deterministic,
// computed by this module from data we already have — replyLanguage from the classification we
// already ran, usedKnowledgeIds from the chunks retrieval already selected, subject from the
// existing buildReplySubject helper, confidence/needsManualAnswer from the retrieval scores.
// This was a deliberate simplification (tasks/plan.md Task 22): asking a ~1-2B local model for a
// full JSON object (schema compliance + RAG grounding + tone, all at once) was unreliable — live
// testing against a real customer email showed only 1/3 runs produced valid, schema-conformant
// output. Asking for plain body text only, with generation "thinking" disabled (see generateDraft
// below), was 5/5 reliable in the same live tests and also stopped the model from mistranslating
// verbatim facts (style names, etc.) that it should have copied as-is.
//
// Written in Russian (tasks/plan.md Task 26, at the user's request): this is the team's working
// language and the site's canonical language (KNOWLEDGE_CANONICAL_LANGUAGE=ru for this
// deployment); the target reply language is still selected explicitly per-email via
// LANGUAGE_NAMES_RU, independent of the prompt's own language. The persona line matters for tone,
// not just decoration — a small model given no identity tends to answer like a generic search
// summary; asked to be a studio's own consultant, it addresses the parent/student directly.
// `instructions` may contain the `{{replyLanguage}}` placeholder (see DEFAULT_PROMPT_CONTENT) —
// substituted here rather than left to the model, since the target language is a deterministic
// pipeline decision (the already-run classification), not something free text should guess at.
const buildRagV2DraftPrompt = (persona: string, context: DraftContext, ragV2: NonNullable<DraftContext['ragV2']>): string => {
    const built = buildRagV2Prompt({
        persona,
        understanding: ragV2.understanding,
        knowledge: ragV2.knowledge,
        customerMessage: context.email.normalizedBody,
        crmData: context.contact ? JSON.stringify(context.contact) : undefined,
        correction: ragV2.correction,
        characterBudget: ragV2.characterBudget,
    });
    ragV2.onPromptBuilt?.(built);
    return built.prompt;
};

export const buildDraftBodyPrompt = (instructions: string, context: DraftContext) => {
    const persona = instructions.split('{{replyLanguage}}').join(LANGUAGE_NAMES_RU[context.classification.language]);
    return context.ragV2 ? buildRagV2DraftPrompt(persona, context, context.ragV2) : buildFlatDraftBodyPrompt(persona, context);
};

const buildFlatDraftBodyPrompt = (persona: string, context: DraftContext) => [
    persona,
    '',
    `ПИСЬМО_КЛИЕНТА: ${context.email.normalizedBody}`,
    context.contact ? `ДАННЫЕ_CRM: ${JSON.stringify(context.contact)}` : '',
    context.knowledge.length ? `ЗНАНИЯ:\n${context.knowledge.map((chunk) => `- ${chunk.content}`).join('\n')}` : 'ЗНАНИЯ: (ничего не найдено)',
].filter(Boolean).join('\n');

export class OllamaLlmClient implements LlmClient, DraftLlmClient {
    public readonly provider = DRAFT_PROVIDERS.OLLAMA;
    public readonly model: string;
    public readonly contextLength: number;
    private readonly config: AiConfig;
    private readonly fetchImpl: typeof fetch;
    private readonly prompts: AiPromptRepository;
    private readonly promptOverrides: { classificationPromptId?: number; draftBodyPromptId?: number };
    private readonly onMetric?: (metric: LlmCallMetric) => void;

    public constructor(options: OllamaLlmClientOptions = {}) {
        this.config = options.config ?? aiConfig;
        this.model = this.config.ollamaModel;
        this.contextLength = this.config.contextLength;
        this.fetchImpl = options.fetchImpl ?? fetch;
        this.prompts = options.promptRepository ?? new PrismaAiPromptRepository();
        this.promptOverrides = options.promptOverrides ?? {};
        this.onMetric = options.onMetric;
    }

    private async resolveInstructions(slot: 'CLASSIFICATION' | 'DRAFT_BODY', overrideId?: number): Promise<string> {
        if (overrideId) return (await this.prompts.getContentById(overrideId)) ?? DEFAULT_PROMPT_CONTENT[slot];
        return this.prompts.getActiveContent(slot);
    }

    // No `format: "json"` here (see tasks/plan.md Task 24): it was added to stop qwen3 wrapping
    // output in markdown, and did for a while, but was later confirmed live to also make
    // classification — not just drafting — reliably return an empty `{}` for this exact prompt,
    // independent of prompt length or num_ctx. Plain generation plus schema validation + repair
    // retry (in classifyEmail) was 100% reliable across repeated live tests and is what drafting
    // already uses.
    private async requestClassification(
        instructions: string,
        input: NormalizedEmailInput,
        invalidOutput?: string,
    ): Promise<{ raw: string; durationMs: number; promptTokens: number; completionTokens: number }> {
        const start = Date.now();
        const response = await this.fetchImpl(`${this.config.ollamaUrl.replace(/\/$/, '')}/api/generate`, {
            method: 'POST',
            headers: { 'content-type': 'application/json' },
            body: JSON.stringify({
                model: this.config.ollamaModel,
                prompt: buildClassificationPrompt(instructions, input, invalidOutput),
                stream: false,
                keep_alive: this.config.keepAlive,
                options: {
                    num_ctx: this.config.contextLength,
                    temperature: this.config.temperature,
                },
            }),
        });
        const durationMs = Date.now() - start;

        if (!response.ok) {
            throw new Error(`Ollama classification failed with HTTP ${response.status}`);
        }

        const parsedBody = await response.json();
        const raw = ollamaResponseSchema(parsedBody);
        const usage = extractOllamaTokenUsage(parsedBody);
        return { raw, durationMs, promptTokens: usage.promptTokens ?? 0, completionTokens: usage.completionTokens ?? 0 };
    }

    public async classifyEmail(input: NormalizedEmailInput): Promise<EmailClassification> {
        let invalidOutput: string | undefined;
        const instructions = await this.resolveInstructions('CLASSIFICATION', this.promptOverrides.classificationPromptId);
        let totalDurationMs = 0;
        let totalPromptTokens = 0;
        let totalCompletionTokens = 0;

        for (let attempt = 0; attempt < 2; attempt += 1) {
            const { raw, durationMs, promptTokens, completionTokens } = await this.requestClassification(instructions, input, invalidOutput);
            totalDurationMs += durationMs;
            totalPromptTokens += promptTokens;
            totalCompletionTokens += completionTokens;
            try {
                const classification = emailClassificationSchema.parse(JSON.parse(raw));
                this.onMetric?.({
                    durationMs: totalDurationMs,
                    callCount: attempt + 1,
                    promptTokens: totalPromptTokens || undefined,
                    completionTokens: totalCompletionTokens || undefined,
                    totalTokens: (totalPromptTokens || totalCompletionTokens) ? totalPromptTokens + totalCompletionTokens : undefined,
                });
                return classification;
            } catch (error) {
                if (attempt === 1) {
                    throw new Error(`Ollama returned invalid classification JSON after one repair retry: ${String(error)}`);
                }
                invalidOutput = raw;
            }
        }

        throw new Error('Ollama classification failed');
    }

    public async generateDraft(context: DraftContext): Promise<EmailDraft> {
        const maxAttempts = 2;
        let lastError: unknown;
        const instructions = await this.resolveInstructions('DRAFT_BODY', this.promptOverrides.draftBodyPromptId);
        let totalDurationMs = 0;
        let totalPromptTokens = 0;
        let totalCompletionTokens = 0;
        for (let attempt = 0; attempt < maxAttempts; attempt += 1) {
            const start = Date.now();
            const response = await this.fetchImpl(`${this.config.ollamaUrl.replace(/\/$/, '')}/api/generate`, {
                method: 'POST',
                headers: { 'content-type': 'application/json' },
                body: JSON.stringify({
                    model: this.config.ollamaModel,
                    prompt: buildDraftBodyPrompt(instructions, context),
                    stream: false,
                    // Confirmed live: disabling the reasoning phase for THIS call (unlike
                    // classifyEmail, where it stays on — see classifyEmail's comment) made body
                    // generation faster, 100% reliable in testing, and stopped the model from
                    // "creatively" mistranslating knowledge facts during its reasoning.
                    think: false,
                    keep_alive: this.config.keepAlive,
                    options: { num_ctx: this.config.contextLength, temperature: this.config.temperature },
                }),
            });
            totalDurationMs += Date.now() - start;
            if (!response.ok) throw new Error(`Ollama draft generation failed with HTTP ${response.status}`);
            const parsedBody = await response.json();
            const usage = extractOllamaTokenUsage(parsedBody);
            totalPromptTokens += usage.promptTokens ?? 0;
            totalCompletionTokens += usage.completionTokens ?? 0;
            const body = ollamaResponseSchema(parsedBody).trim().slice(0, 6_000);
            if (body.length >= 5) {
                this.onMetric?.({
                    durationMs: totalDurationMs,
                    callCount: attempt + 1,
                    promptTokens: totalPromptTokens || undefined,
                    completionTokens: totalCompletionTokens || undefined,
                    totalTokens: (totalPromptTokens || totalCompletionTokens) ? totalPromptTokens + totalCompletionTokens : undefined,
                });
                return buildDeterministicDraft(context, body);
            }
            lastError = new Error(`Ollama returned an empty or too-short draft body: ${JSON.stringify(body)}`);
        }
        throw lastError instanceof Error ? lastError : new Error('Ollama draft generation failed');
    }
}

export const buildDeterministicDraft = (context: DraftContext, body: string): EmailDraft => {
    const topScore = context.knowledge[0]?.score ?? 0;
    const draft: EmailDraft = {
        replyLanguage: context.classification.language,
        subject: buildReplySubject(context.email.subject),
        body,
        // Bounded by retrieval confidence, not self-reported by the model — a small local model
        // grading its own answer is not a reliable signal.
        confidence: Math.max(0, Math.min(context.classification.confidence, topScore || context.classification.confidence)),
        // Weak/absent retrieval is the deterministic proxy for "needs a human to check this" —
        // see CONFIDENT_KNOWLEDGE_SCORE.
        needsManualAnswer: context.knowledge.length === 0 || topScore < CONFIDENT_KNOWLEDGE_SCORE,
        usedKnowledgeIds: context.knowledge.map((chunk) => chunk.id),
    };
    return emailDraftSchema.parse(draft);
};
