FROM node:20-alpine AS build

WORKDIR /app

ARG CLIENT_API_URL
ENV CLIENT_API_URL=${CLIENT_API_URL}

COPY client/package*.json ./
RUN npm ci --include=dev

COPY client/. .
RUN npm run build:prod

FROM nginx:1.27-alpine

COPY docker/client/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
