import { createHash, randomUUID } from 'node:crypto';
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';

// Private file storage behind one interface, so the local volume can later be swapped for an
// object store without touching the modules that keep photos and documents.
export interface StorageProvider {
    readonly name: string;
    put(key: string, content: Buffer): Promise<void>;
    read(key: string): Promise<Buffer>;
    remove(key: string): Promise<void>;
}

const KEY_PATTERN = /^[a-z0-9][a-z0-9._-]*(\/[a-z0-9][a-z0-9._-]*)*$/;

// Keys are generated by the server, but they are still checked: a key may never leave the root.
export const resolveStoragePath = (root: string, key: string): string => {
    if (!KEY_PATTERN.test(key) || key.includes('..')) throw new Error('Invalid storage key');
    const absoluteRoot = path.resolve(root);
    const target = path.resolve(absoluteRoot, key);
    if (!target.startsWith(`${absoluteRoot}${path.sep}`)) throw new Error('Invalid storage key');
    return target;
};

export const createLocalStorage = (root: string): StorageProvider => ({
    name: 'LOCAL',
    put: async (key, content) => {
        const target = resolveStoragePath(root, key);
        await mkdir(path.dirname(target), { recursive: true });
        await writeFile(target, content, { flag: 'wx' });
    },
    read: key => readFile(resolveStoragePath(root, key)),
    remove: key => rm(resolveStoragePath(root, key), { force: true }),
});

export const storageRoot = (env: NodeJS.ProcessEnv = process.env): string => path.resolve(process.cwd(), env.STORAGE_ROOT || 'private-uploads');

let provider: StorageProvider | null = null;
export const storage = (): StorageProvider => {
    provider = provider ?? createLocalStorage(storageRoot());
    return provider;
};

// "folder/<uuid>.<ext>": nothing from the uploaded file name ever becomes part of a path.
export const newStorageKey = (folder: string, extension: string): string => `${folder}/${randomUUID()}.${extension}`;

export const sha256 = (content: Buffer): string => createHash('sha256').update(content).digest('hex');
